export { Error } from './Error'
export { Home } from './Home'
export { SlideAbout } from './SlideAbout'
export { SlideProjects } from './SlideProjects'
export { SlideWelcome } from './SlideWelcome'
export { SlideContacts } from './SlideContacts'
export { RotateControl } from './RotateControl'
export { Loading } from './Loading'
